<a href="https://colab.research.google.com/github/toruuno/DNN_d1d2/blob/master/1_1_forward_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 準備

## Googleドライブのマウント

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## sys.pathの設定

以下では，Googleドライブのマイドライブ直下にDNN_codeフォルダを置くことを仮定しています．必要に応じて，パスを変更してください．

In [ ]:
import sys
sys.path.append('/content/drive/My Drive/DNN_code')
sys.path.append('/content/drive/My Drive/common')
sys.path.append('/content/drive/My Drive')

# importと関数定義

In [ ]:
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    #print("shape: " + str(x.shape))
    print("")


# 順伝播（単層・単ユニット）

In [ ]:
# 順伝播（単層・単ユニット）

def report(W,b,x,u,z):
  print("バイアス(b)={} 総出力(u)={} 中間出力(z)={}".format(b,u,z))

#とりあえず「数値初期化を振れ」という課題と受け止めて改変してみた
#
#気づいた点は・・・
#配列の初期化で型(というか配列の次元数等)は合わせないと気持ち悪い
#という程度
#計算は単純なベクトルの内積＋活性化関数(ReLU)の結果表示に過ぎず
#活性化関数の動きを見るために重みマイナスの初期化も追加している(一応)

# 重み
Ws = []
Ws.append(np.array([[0.1], [0.2]]))

## 試してみよう_配列の初期化
Ws.append(np.zeros(2).reshape(2,1))
Ws.append(np.ones(2).reshape(2,1))
Ws.append(np.random.rand(2).reshape(2,1))
Ws.append(np.random.randint(5, size=(2)).reshape(2,1))
Ws.append(np.array([[-1.1], [-0.9]]))  #マイナス値追加

# 入力値
x = np.array([2, 3])

for W in Ws:
  print("######################")
  print_vec("入力(x)=", x)
  print_vec("重み(W)=", W)

  # バイアス
  Bs=[]
  Bs.append(0.5)

  ## 試してみよう_数値の初期化
  Bs.append(np.random.rand()) # 0~1のランダム数値
  Bs.append(np.random.uniform(low=-5,high=5,size=1)[0])  # -5~5のランダム数値

  for b in Bs:
    print("-----------------")
    #print_vec("バイアス", b)

    # 総入力
    u = np.dot(x, W) + b
    #print_vec("総入力", u)

    # 中間層出力
    z = functions.relu(u)
    #print_vec("中間層出力", z)

    report(W,b,x,u,z)

######################
*** 入力(x)= ***
[2 3]

*** 重み(W)= ***
[[0.1]
 [0.2]]

-----------------
バイアス(b)=0.5 総出力(u)=[1.3] 中間出力(z)=[1.3]
-----------------
バイアス(b)=0.09420273217732267 総出力(u)=[0.89420273] 中間出力(z)=[0.89420273]
-----------------
バイアス(b)=-1.389515815361909 総出力(u)=[-0.58951582] 中間出力(z)=[0.]
######################
*** 入力(x)= ***
[2 3]

*** 重み(W)= ***
[[0.]
 [0.]]

-----------------
バイアス(b)=0.5 総出力(u)=[0.5] 中間出力(z)=[0.5]
-----------------
バイアス(b)=0.03550903176033027 総出力(u)=[0.03550903] 中間出力(z)=[0.03550903]
-----------------
バイアス(b)=0.46358348540806915 総出力(u)=[0.46358349] 中間出力(z)=[0.46358349]
######################
*** 入力(x)= ***
[2 3]

*** 重み(W)= ***
[[1.]
 [1.]]

-----------------
バイアス(b)=0.5 総出力(u)=[5.5] 中間出力(z)=[5.5]
-----------------
バイアス(b)=0.7961427208560042 総出力(u)=[5.79614272] 中間出力(z)=[5.79614272]
-----------------
バイアス(b)=-4.488571968986529 総出力(u)=[0.51142803] 中間出力(z)=[0.51142803]
######################
*** 入力(x)= ***
[2 3]

*** 重み(W)= ***
[[0.81190239]
 [0.92668262]]

---

# 順伝播（単層・複数ユニット）


In [ ]:
# 順伝播（単層・複数ユニット）

#こちらについても重みを振る課題と解釈
#
#気づいた点・・・
#複数ユニットの中間出力、NN全体の最終段出力層ならば3値分類ということで
#シグモイドでなくソフトマックスを活性化関数に使うべき
#NN全体の中間層だとしてもReLUを選択すべき
#最終段の場合確率が正しく出てないことになる
#NN全体の中間層の場合、勾配消失問題を引き起こす可能性が高くなる

# 重み
Ws = []
Ws.append(np.array([
    [0.1, 0.2, 0.3], 
    [0.2, 0.3, 0.4], 
    [0.3, 0.4, 0.5],
    [0.4, 0.5, 0.6]
]))

## 試してみよう_配列の初期化
Ws.append(np.zeros((4,3)))
Ws.append(np.ones((4,3)))
Ws.append(np.random.rand(4,3))
Ws.append(np.random.randint(5, size=(4,3)))

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)


for W in Ws:
  print("############################")
  print_vec("重み", W)

  #  総入力
  u = np.dot(x, W) + b
  print_vec("総入力", u)

  # 中間層出力
  z = functions.sigmoid(u)
  print_vec("中間層出力", z)


*** バイアス ***
[0.1 0.2 0.3]

*** 入力 ***
[ 1.  5.  2. -1.]

############################
*** 重み ***
[[0.1 0.2 0.3]
 [0.2 0.3 0.4]
 [0.3 0.4 0.5]
 [0.4 0.5 0.6]]

*** 総入力 ***
[1.4 2.2 3. ]

*** 中間層出力 ***
[0.80218389 0.90024951 0.95257413]

############################
*** 重み ***
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

*** 総入力 ***
[0.1 0.2 0.3]

*** 中間層出力 ***
[0.52497919 0.549834   0.57444252]

############################
*** 重み ***
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

*** 総入力 ***
[7.1 7.2 7.3]

*** 中間層出力 ***
[0.99917558 0.99925397 0.99932492]

############################
*** 重み ***
[[0.49341505 0.58349974 0.93929935]
 [0.94354008 0.11169243 0.84355497]
 [0.34602815 0.10082727 0.38340907]
 [0.5103548  0.96110308 0.37151262]]

*** 総入力 ***
[5.49281697 0.58251334 5.8523797 ]

*** 中間層出力 ***
[0.99590064 0.64164552 0.99713518]

############################
*** 重み ***
[[1 2 2]
 [1 3 0]
 [0 0 3]
 [1 4 4]]

*** 総入力 ***
[ 5.1 13.2  4.3]

*** 中間層出力 ***
[0.9939402  0.99999815 

# 順伝播（3層・複数ユニット）

In [ ]:
# 順伝播（3層・複数ユニット）

# 課題はパラメータのランダム生成とそのshape表示
# ということでやってみた

def print_vec_sp(text, vec):
    print("*** " + text + " ***")
    print(vec)
    print("shape: " + str(vec.shape))
    print("")

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network(seed=1):
    print("##### ネットワークの初期化 #####")
    network = {}
    
    np.random.seed(seed=seed)
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(2,3)
    #np.array([
    #    [0.1, 0.3, 0.5],
    #    [0.2, 0.4, 0.6]
    #])
    network['W2'] = np.random.rand(3,2)
    #np.array([
    #    [0.1, 0.4],
    #    [0.2, 0.5],
    #    [0.3, 0.6]
    #])
    network['W3'] = np.random.rand(2,2)
    #np.array([
    #    [0.1, 0.3],
    #    [0.2, 0.4]
    #])
    network['b1'] = np.random.rand(1,3)  #np.array([0.1, 0.2, 0.3])
    network['b2'] = np.random.rand(1,2)  #np.array([0.1, 0.2])
    network['b3'] = np.random.rand(1,2)  #np.array([1, 2])

    print_vec_sp("重み1", network['W1'] )
    print_vec_sp("重み2", network['W2'] )
    print_vec_sp("重み3", network['W3'] )
    print_vec_sp("バイアス1", network['b1'] )
    print_vec_sp("バイアス2", network['b2'] )
    print_vec_sp("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", z1)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1, z2

# 入力値
x = np.array([1., 2.])
print_vec("入力", x)

# ネットワークの初期化=>結合 その1
network =  init_network(seed=10)
y, z1, z2 = forward(network, x)

# ネットワークの初期化=>結合 その2
network =  init_network(seed=20)
y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2.]

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]]
shape: (2, 3)

*** 重み2 ***
[[0.19806286 0.76053071]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]]
shape: (3, 2)

*** 重み3 ***
[[0.00394827 0.51219226]
 [0.81262096 0.61252607]]
shape: (2, 2)

*** バイアス1 ***
[[0.72175532 0.29187607 0.91777412]]
shape: (1, 3)

*** バイアス2 ***
[[0.71457578 0.54254437]]
shape: (1, 2)

*** バイアス3 ***
[[0.14217005 0.37334076]]
shape: (1, 2)

##### 順伝播開始 #####
*** 総入力1 ***
[[2.99068373 1.30964204 2.00101565]]

*** 中間層出力1 ***
[[2.99068373 1.30964204 2.00101565]]

*** 総入力2 ***
[[2.89980955 4.84049973]]

*** 出力1 ***
[[2.99068373 1.30964204 2.00101565]]

出力合計: 6.301341416411899
##### ネットワークの初期化 #####
*** 重み1 ***
[[0.5881308  0.89771373 0.89153073]
 [0.81583748 0.03588959 0.69175758]]
shape: (2, 3)

*** 重み2 ***
[[0.37868094 0.51851095]
 [0.65795147 0.19385022]
 [0.2723164  0.71860593]]
shape: (3, 2)

*** 重み3 ***
[[0.78300361 0.85032764]
 

# 多クラス分類（2-3-4ネットワーク）

In [ ]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう
# という課題と解釈して変更を実施してみた
# 初期値を線形結合しただけで良い値が出てしまうのが気に入らないので
# 適当に誤差が見えるようにパラメータ初期値はいじっている

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5, 0.7, 0.9],
        [0.2, 0.4, 0.6, 0.8, 1.0],
        [-0.3, -0.5, -0.7, -0.9, -1.1]
    ])
    # = np.array([
    #    [0.1, 0.3, 0.5],
    #    [0.2, 0.4, 0.6]
    #])
    network['W2'] = np.array([
        [0.1, 0.4, 0.7, 1.0],
        [0.2, 0.5, 0.8, 1.1],
        [0.3, 0.6, 0.9, 1.2],
        [0.4, 0.7, 1.0, 1.3],
        [0.5, 0.8, 1.1, 1.4]
    ])
    #np.array([
    #    [0.1, 0.4, 0.7, 1.0],
    #    [0.2, 0.5, 0.8, 1.1],
    #    [0.3, 0.6, 0.9, 1.2]
    #])
    network['b1'] = np.array([0.1, 0.2, 0.3, 0.4, 0.5]) #np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2, 0.3, 0.4]) #変更なし
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
#x = np.array([1., 2.])
x = np.array([1., 2., 3.])

# 目標出力
d = np.array([0, 0, 0, 1])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[ 0.1  0.3  0.5  0.7  0.9]
 [ 0.2  0.4  0.6  0.8  1. ]
 [-0.3 -0.5 -0.7 -0.9 -1.1]]

*** 重み2 ***
[[0.1 0.4 0.7 1. ]
 [0.2 0.5 0.8 1.1]
 [0.3 0.6 0.9 1.2]
 [0.4 0.7 1.  1.3]
 [0.5 0.8 1.1 1.4]]

*** バイアス1 ***
[0.1 0.2 0.3 0.4 0.5]

*** バイアス2 ***
[0.1 0.2 0.3 0.4]

##### 順伝播開始 #####
*** 総入力1 ***
[-3.00000000e-01 -2.00000000e-01 -1.00000000e-01 -3.33066907e-16
  1.00000000e-01]

*** 中間層出力1 ***
[0.  0.  0.  0.  0.1]

*** 総入力2 ***
[0.15 0.28 0.41 0.54]

*** 出力1 ***
[0.20355243 0.23181128 0.26399327 0.30064303]

出力合計: 1.0

##### 結果表示 #####
*** 出力 ***
[0.20355243 0.23181128 0.26399327 0.30064303]

*** 訓練データ ***
[0 0 0 1]

*** 誤差 ***
1.2018313485030945



# 回帰（2-3-2ネットワーク）

In [ ]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう
# という課題と解釈して変更を実施してみた
# 初期値を線形結合しただけで良い値が出てしまうのが気に入らないので
# 適当に誤差が見えるようにパラメータ初期値はいじっている

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.array([
        [ 0.1, -0.3,  0.5, -0.7,  0.9],
        [ 0.2,  0.4, -0.6,  0.8, -1.0],
        [-0.3,  0.5,  0.7,  0.9, -1.1]
    ])
    #np.array([
    #    [0.1, 0.3, 0.5],
    #    [0.2, 0.4, 0.6]
    #])
    network['W2'] = np.array([
        [-0.1,  0.4,  0.1,  0.4],
        [ 0.2, -0.5,  0.2,  0.5],
        [ 0.3,  0.6, -0.3,  0.6],
        [ 0.4,  0.7,  0.4, -0.7],
        [ 0.5, -0.8,  0.5,  0.8]
    ])
    #np.array([
    #    [0.1, 0.4],
    #    [0.2, 0.5],
    #    [0.3, 0.6]
    #])
    network['b1'] = np.array([0.1, 0.2, 0.3, 0.2, 0.1])  #np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2, 0.1, 0.0]) #np.array([0.1, 0.2])
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))
    
    return y, z1

# 入力値
#x = np.array([1., 2.])
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
#d = np.array([2., 4.])
d = np.array([2., 4., 6., 8.])
# 誤差
loss = functions.mean_squared_error(d, y)
## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[ 0.1 -0.3  0.5 -0.7  0.9]
 [ 0.2  0.4 -0.6  0.8 -1. ]
 [-0.3  0.5  0.7  0.9 -1.1]]

*** 重み2 ***
[[-0.1  0.4  0.1  0.4]
 [ 0.2 -0.5  0.2  0.5]
 [ 0.3  0.6 -0.3  0.6]
 [ 0.4  0.7  0.4 -0.7]
 [ 0.5 -0.8  0.5  0.8]]

*** バイアス1 ***
[0.1 0.2 0.3 0.2 0.1]

*** バイアス2 ***
[0.1 0.2 0.1 0. ]

##### 順伝播開始 #####
*** 総入力1 ***
[-0.3  2.2  1.7  3.8 -4.3]

*** 中間層出力1 ***
[0.  2.2 1.7 3.8 0. ]

*** 総入力2 ***
[ 2.57  2.78  1.55 -0.54]

*** 出力1 ***
[ 2.57  2.78  1.55 -0.54]

出力合計: 7.700000000000001

##### 結果表示 #####
*** 中間層出力 ***
[0.  2.2 1.7 3.8 0. ]

*** 出力 ***
[ 2.57  2.78  1.55 -0.54]

*** 訓練データ ***
[2. 4. 6. 8.]

*** 誤差 ***
11.818425000000001



# 2値分類（2-3-1ネットワーク）

In [ ]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-1 に変更してみよう
# という課題と解釈して変更を実施してみた
# 初期値を線形結合しただけで良い値が出てしまうのが気に入らないので
# 適当に誤差が見えるようにパラメータ初期値はいじっている

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    np.random.seed(seed=5)
    network = {}
    network['W1'] = np.random.rand(5,10) #面倒なのでnp.randomを利用
    #np.array([
    #    [0.1, 0.3, 0.5],
    #    [0.2, 0.4, 0.6]
    #])
    network['W2'] =  np.array([
        [ 0.2],
        [-0.4],
        [ 0.2],
        [-0.4],
        [ 0.2],
        [-0.4],
        [ 0.2],
        [-0.4],
        [ 0.2],
        [-0.4]
    ])
    #np.array([
    #    [0.2],
    #    [0.4],
    #    [0.6]
    #])
    network['b1'] = np.random.rand(1,10)[0]   #np.array([0.1, 0.2, 0.3])  面倒なのでnp.randomを利用
    network['b2'] = np.array([0.1])           #変更なし
    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']    

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2 
    # 出力層の総出力
    y = functions.sigmoid(u2)
            
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1


# 入力値
#x = np.array([1., 2.])
x = np.array([1., 2., 3., 4., 5.])
# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[ 4.34683161  8.46070794  9.1242967   9.81432736  3.44523434  6.50174809
  7.97004415  8.69074996 11.87955976  9.15350291]

*** 中間層出力1 ***
[ 4.34683161  8.46070794  9.1242967   9.81432736  3.44523434  6.50174809
  7.97004415  8.69074996 11.87955976  9.15350291]

*** 総入力2 ***
[-9.59522119]

*** 出力1 ***
[6.80485427e-05]

出力合計: 79.38700282574678

##### 結果表示 #####
*** 中間層出力 ***
[ 4.34683161  8.46070794  9.1242967   9.81432736  3.44523434  6.50174809
  7.97004415  8.69074996 11.87955976  9.15350291]

*** 出力 ***
[6.80485427e-05]

*** 訓練データ ***
[1]

*** 誤差 ***
9.593820783821917

